on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  NODE_VERSION: '12.x'

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ env.NODE_VERSION }}

    - name: npm install, build, and test
      run: |
          npm install
          npm run build --if-present
          npm run test --if-present

    - name: Generate deployment package
      run: ls
      run: zip -r deploy.zip * -x "**node_modules**"
      run: ls
      
    - name: Get timestamp
      uses: gerred/actions/current-time@master
      id: current-time
      
